a = "HIT OR MISS, I GUESS THEY NEVER MISS HUH?"
b = "YOU GOT A BOYFRIEND I BET HE DOESN'T KISS YA!"
c = "HE GON FIND ANOTHER GIRL THEN HE WONT MISS YA!"
d = "HE GON SKIRT THEN HIT THE DAB LIKE WIZ KHALIFA!!"

while a is not b:
    print (a, b, c, d) * 234234
